version: "3"
services:

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "3001"
    extra_hosts:
      - "site1.loc:172.17.0.1"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    networks:
      - app-network
      
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email example@mail.ru --agree-tos --no-eff-email --staging -d example.ru  -d www.example.ru

  bot:
    build: ./
    container_name: telegram_bot
    depends_on:
      - webserver
      - certbot
    networks:
      - app-network
    ports:
      - "3001"
      
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /root/bot/views/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/bot/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
